### ISSUE TITLE
README.rst to README.md to support pypi package description

### ISSUE THREAD

**Issue by kenessajr** [pindo-io/pindo-cli#9]
The Pindo-CLI has no project description on pypi, seems like pypi work entirely with markdown. For both use changing the README.

<img width="1397" alt="Screen Shot 2019-04-24 at 17 32 49" src="https://user-images.githubusercontent.com/5709541/56672786-50134800-66b7-11e9-8212-932639e9b473.png">
rst file README.md will be solving the issue.

**Comment by OlivierJM** [comment]
I will take up this one. 😀

**Comment by kenessajr** [comment]
Thanks, @OlivierJM now the [pindo-cli](https://pypi.org/project/pindo-cli/) can have a description on pypi.🍻

<img width="1479" alt="Screen Shot 2019-04-28 at 10 30 19" src="https://user-images.githubusercontent.com/5709541/56861416-cefece00-69a0-11e9-9b69-f5e7aceee0db.png">

**Comment by OlivierJM** [comment]
Awesome

**Comment by OlivierJM** [comment]
I am sure the issue can now be closed
